
image: gitpod/workspace-postgres

tasks:
  - init: npm install
    command: |
      export HMR_HOST=$(gp url 3000)
      npm run dev
    env:
      DATABASE_URL: postgres://gitpod@localhost/fields
  - command: npx prisma studio
    env:
      DATABASE_URL: postgres://gitpod@localhost/fields

ports:
  - port: 3000 # web app
    onOpen: open-browser
  - port: 5432 # db
    onOpen: ignore
  - port: 5555 # prisma web app
    onOpen: open-browser

vscode:
  extensions:
    - svelte.svelte-vscode
    - Prisma.prisma

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true